### ISSUE TITLE
Doctrin PHP7 compatibility

### ISSUE THREAD

**Issue by splitbrain** [dokufreaks/dokuwiki-translation#106]
We currently get the following warning on PHP 7

`PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/translate/htdocs/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php 
on line 2665`

**Comment by splitbrain** [comment]
I monkey-patched a break in, because I think that's what the authors wanted there. But we should do a proper dependency update

**Comment by Klap-in** [comment]
I’m now working on an upgrade to the most recent version of Symfony. Nice that you get a lot with such a framework, but of course with a learning curve. I’m now at version 4.4. I will do a PR some where coming weeks.

**Comment by Klap-in** [comment]
Will be solved with #112
