### ISSUE TITLE
Translation submissions to the git repository are paused

### ISSUE THREAD

**Issue by dwp-forge** [dokufreaks/dokuwiki-translation#107]
I have one of my plugins listed in the translation tool and keep getting outdated translation updates because the tool uses an old code base as a reference. The [settings page](https://translate.dokuwiki.org/plugin/batchedit/settings) mentions that there are 3 errors (whatever that may mean) and translation submissions are paused. Yet I do get [new translation submissions](https://github.com/dwp-forge/batchedit/pull/47), it's just that they are no longer relevant.

What could be a reason for that?

**Comment by Klap-in** [comment]
Then there have been errors, or for example in the simple parser of the tool or in its use of git that created errors in the past. After 3 errors it stops trying. We can manually reset the tool. Not sure when I can do that. If it takes too long, please remember me.

**Comment by dwp-forge** [comment]
Thanks for the reset.
