### ISSUE TITLE
Templater plugin errors count 3

### ISSUE THREAD

**Issue by nerun** [dokufreaks/dokuwiki-translation#115]
At DokuWiki Localization, my plugin has 3 errors count, can someone help me?

- [Translate DokuWiki settings page](https://translate.dokuwiki.org/plugin/templater/settings)
- [Templater Plugin at DokuWiki](https://www.dokuwiki.org/plugin:templater)
- [Templater Plugin at GitHub](https://github.com/nerun/dokuwiki-plugin-templater)

**Comment by Klap-in** [comment]
Hi, sorry for the slow reply.
I saw you did already some changes in the file structure. I have reset the error counter, and now the import was successful!
Enjoy the tool!

**Comment by Klap-in** [comment]
Ah, pardon I misread it. It was not yet fixed, I will have a look.

**Comment by Klap-in** [comment]
Do you got also an email with the error message? that makes it easier to look for me.

**Comment by nerun** [comment]
YES

First Error:
```
Hello,

the import of your Templater Plugin failed.
The DokuWiki localization folders are missing.

Please note that the DokuWiki translation tool only supports DokuWiki localization format.
For further information on localization read https://www.dokuwiki.org/devel:localization.

Regards,
DokuWiki Translation Tool
/
```
Second:
```
Hello,

the automatic update of your Templater Plugin failed.
I wasn't able to pull from the given repository.
Please ensure that the given URL is publicly accessible.

The git URL was https://github.com/nerun/dokuwiki-plugin-templater.git

Regards,
DokuWiki Translation Tool
/
```

**Comment by Klap-in** [comment]
The first error was solved by your update of the file structure. The second error was caused by a difference in branch name. Tool searched for 'master', while you repository uses 'main'. Changing the branch name in the tool fixed this issue.
Enjoy!
