### ISSUE TITLE
add interface to change plugin settings

### ISSUE THREAD

**Issue by dom-mel** [dokufreaks/dokuwiki-translation#19]
This should be added to error emails as well

**Comment by Klap-in** [comment]
How to identify the plugin authors?

By sending confirmation urls with unique codes....?

or with real authentication system? which? of doku forum? how to link plugin author with doku forum login?

**Comment by dom-mel** [comment]
Either DokuWiki forum (require a forum accout to add a New plugin-old ones must be mapped manually) or simple auth tokens via mail to the owners mail

**Comment by Klap-in** [comment]
Thanks for your response!
I think I will go for auth tokens via mail. That is the simplest, and not dependent on external systems.

**Comment by Klap-in** [comment]
Editing email, English readonly, url and branch is implemented.
