### ISSUE TITLE
"Add a Plugin"-Link doesn't work after adding a plugin

### ISSUE THREAD

**Issue by dploeger** [dokufreaks/dokuwiki-translation#44]
After adding a plugin I cannot click on the "Add a Plugin" link in the upper left corner. At least it doesn't do anything.

Chrome 28.0.1500.95 on OS X 10.8.4 here.

**Comment by Klap-in** [comment]
It is a link with `href="#"`, so it points to current page without reloading.

Solution: make the url of last breadcrumb just plain text. Or is this linkified on purpose?

**Comment by Klap-in** [comment]
@dom-mel why are you linking to `href="#"`? looks useless in eyes of end users..
