### ISSUE TITLE
Translating templates

### ISSUE THREAD

**Issue by dploeger** [dokufreaks/dokuwiki-translation#45]
As templates use the same method of translation, couldn't they be added as well?

**Comment by selfthinker** [comment]
Why was this closed? Templates are still not supported.

**Comment by Klap-in** [comment]
Is it correct that `plugin:<pluginname>` is unique and `template:<templatename>` are unique. 
But that `<pluginname>` == `<templatename>` could be true?

What means that url `/extension/<extensionname>` is not possible.

I will go for urls like:
`/plugin/<pluginname>`
`/template/<templatename>`

**Comment by Klap-in** [comment]
The translation tool is updated, and includes now template support. If you meet any issues, please let me know!
