### ISSUE TITLE
' (one) vs." (double)

### ISSUE THREAD

**Issue by alexgearbox** [dokufreaks/dokuwiki-translation#47]
The DokuWiki Translation Tool ignores lines with double quotation mark (") (I use Opera browser v. 12.16)

See the [Source of the numbering Plugin](https://github.com/turnermm/numbering/blob/master/lang/en/settings.php) and [Translate numbering Plugin](http://translate.dokuwiki.org/translate/plugin/numbering?lang=en).

**Comment by Klap-in** [comment]
Your example source shows today 8 strings, and the translation tool as well.

Can I conclude that the issue is fixed? Or do you still experience this issue?

**Comment by Klap-in** [comment]
I checked the code, and some plugins which use double quotes in their strings. Double quotes are processed well by the translation tool.

In old revisions I see that the lines of the Numbering Plugin with double quotes were also lines which had string concatenation `e.g. "text" . "text2"`. The translation tool doesn't support string concatenation, so these lines will break the processing by the translation tool.

**Comment by Klap-in** [comment]
I prefer to keep the parser of the translation tool simple. Therefore I won't implement support for concatenation.
