### ISSUE TITLE
100% with 2 strings to go

### ISSUE THREAD

**Issue by Klap-in** [dokufreaks/dokuwiki-translation#59]
The dokuwiki score was 100%, while 2 strings were untranslated.
Probably because 2/~600 is less than 1%.
Translations with 3 and more untranslated strings are indicated as 99%.

Design question: is it useful to have only 100% when really all strings are translated?

**Comment by selfthinker** [comment]
When translations are missing, it should always be visible in one way or another. I suggest to **round down** the percentage, so even a million strings minus one is 99%.
