### ISSUE TITLE
update seems to fail

### ISSUE THREAD

**Issue by splitbrain** [dokufreaks/dokuwiki-translation#61]
It seems the update mechanism isn't 100% reliable. I got a lot of unmergable translation requests recently, because people worked on an old commit.

For example: the publish plugin has a french translation for 2 weeks now: https://github.com/cosmocode/dokuwiki-plugin-publish/tree/master/lang/fr however the translation interface lists no french at all: http://translate.dokuwiki.org/plugin/publish

**Comment by Klap-in** [comment]
Any information about which errors occur?

**Comment by Klap-in** [comment]
Run fine at the moment. And no clue for specific issues, therefore closed.
