### ISSUE TITLE
documentation for the whole process

### ISSUE THREAD

**Issue by splitbrain** [dokufreaks/dokuwiki-translation#69]
It would be tremendously helpful for people wanting to help with fixing bugs in this tool to have a description on how the whole process work internally. Eg. what are all the folders in the data directory? What gets checked out where? How are language updates stored? How are git repository updates done? and so on. Maybe start a page in the github wiki here with some first pointers?

**Comment by Klap-in** [comment]
I found already https://github.com/dokufreaks/dokuwiki-translation/wiki Nice that you start documentating!

I try to install and setup the whole stuff. I succeed in getting the interface appearing. But all the git handling seems to do nothing. Sofar I have no idea where to look, so if you could provide more details about that process that would be helpful.

Other questions:
- how did you setup the mailing in a development setup? does it require certain software on my machine? (.. i have to check, maybe my local installation cannot send mail at all at the moment...)
- about the settings in app/config/parameters.yml.dist e.g. what is purpose of `git_hub_url`, `featureImport` and  `featureAddTranslationFromDetail`
- I didn't get the idea of why and how using multiple accounts, could you explain that? (you mentioned it here as well https://github.com/dokufreaks/dokuwiki-translation/wiki/Git-interaction)
- Which permissions should I set at least for the GitHub api token on Github?

**Comment by Klap-in** [comment]
@dom-mel Could you explain how you had setup up an alternative account for testing the creation and submision of new languages. (So the alternative for https://github.com/dokuwiki-translate)

- if I use that multiuser setup from that blog, does that require that I provide now always the user when i will perform a git action?

**Comment by Klap-in** [comment]
@dom-mel it would be very useful to understand more about the why and how using the multiuser git accounts. 
Could you please explain more about this? Thanks!

**Comment by Klap-in** [comment]
Most info is now in wiki of this `dokuwiki-translation` repository. 
wrt multiuser, I now got an idea about that some git actions are done via console commands and other via github API.

Additional question are still welcome.
