### ISSUE TITLE
fckgLite now fckg

### ISSUE THREAD

**Issue by turnermm** [dokufreaks/dokuwiki-translation#70]
To bring fckgLite in line with Dokuwiki's naming conventions, I renamed fckgLite to fckg, which is the actual coded name of the plugin.  So, the plugin 'fckgLIte' should be deleted from the translate tool.
I thought it would be safe to do this because fckgLite has generated any translations because it had some code in its settings.php.
Thanks.

**Comment by Andrwe** [comment]
Hi,

I deleted the plugin fckgLite from translation tool.


Regards,
Andrwe

**Comment by Klap-in** [comment]
Thanks!
