### ISSUE TITLE
Adding and keep track of supported languages

### ISSUE THREAD

**Issue by Klap-in** [dokufreaks/dokuwiki-translation#83]
Currently at 2 places languages are added to database:
 - via calculating stats of plugin lang files, every unknown language code is added
https://github.com/dokufreaks/dokuwiki-translation/blob/master/src/org/dokuwiki/translatorBundle/Services/Repository/RepositoryStats.php#L67
 - via dokuwiki:setup command https://github.com/dokufreaks/dokuwiki-translation/blob/master/src/org/dokuwiki/translatorBundle/Command/SetupCommand.php

 - [ before 3rd way of adding is removed by e93b0aa039328271bf346a669f686cb40da1f0ac and e93b0aa039328271bf346a669f686cb40da1f0ac , due to issue #71 ]

Remarks:
- The dokuwiki:setup is only used at very first start.
- The automatically adding via scanning of language files of plugins is undesired

Ideas:
 - Add a command for just adding a language name to database.
 - Or bit more advanced: use a config file to keep track of added language names. This can be used in dokuwiki:setup, but also by update latter on...

**Comment by splitbrain** [comment]
I think having a command would be preferable. I was thinking about that myself.

**Comment by Klap-in** [comment]
Since bb9f21e0a62c4db28b84a3f4eb05a0aa723455d0:
If languages are missing, these could be added to the list in the `dokuwiki:setup` command. If now this command is called all the missing info is included in database, existing entries are skipped.

Some languages added by 66e3630874a233eae307f57edc62dbe778ca8622

**Comment by Klap-in** [comment]
Solution: new languages has to be added to the dokuwiki:setup command, which can be run to add just the missing languages.
