### ISSUE TITLE
Bitbucket not (yet) supported - Remove PyCode plugin

### ISSUE THREAD

**Issue by TorMec** [dokufreaks/dokuwiki-translation#84]
Hi,
as I wrote here https://github.com/dokufreaks/dokuwiki-translation/issues/80 (probably) I did a mistake submitting a wrong url for my plugin.
Now it is still in the process phase, so I think it's better to remove it.

It is stored in a (public) Bitbucket repository and the git clone url is: https://Torpedo@bitbucket.org/Torpedo/pycode.git
The plugin works fine, that is, in Extension Manager you can enable/disable/update it.

So, my question is, is there any kind of restriction against Bitbucket?

Thanks

**Comment by Klap-in** [comment]
Probably the translation tool is not (yet) tested against Bitbucket.
If I got an installation of this tool completely working on my local machine I will test this case.

**Comment by TorMec** [comment]
Yep, maybe Bitbucket is not supported.
Indeed, in some files in /src/org/dokuwiki/translatorBundle/Services, many times are called regular expressions with "github.com" or some thing similar, so "bitbucket.org" will never match.

**Comment by splitbrain** [comment]
The translation tool is hosting agnostic. However you need to provide a proper public git repository. In your case that's https://bitbucket.org/Torpedo/pycode.git 

Your plugin was imported successfully now.

**Comment by TorMec** [comment]
I would not never thought to use that link since, in the Bitbucket's dashboard, the clone button gives ''git clone https://Torpedo@bitbucket.org/Torpedo/pycode.git'' and I use this to clone in local.

For a Bitbucket user, the string ''git clone url'', in the form, is a little bit deceptive.

So GitHub and Bitbucket have a url of the same form:
GitHub: ''https://github.com/<user>/<name-repo>.git''
Bitbucket: ''https://bitbucket.org/<user>/<name-repo>.git''

By the way,
many thanks!
