### ISSUE TITLE
Some problem with Wrap & EditTable plugins translation

### ISSUE THREAD

**Issue by nelidimitrova** [dokufreaks/dokuwiki-translation#87]
Hello. I have a problem with translation of Wrap plugin. I sent my Bulgarian translation two times and see "Thank you" page. But I don't see my translation in https://github.com/selfthinker/dokuwiki_plugin_wrap/network
Same problem with edittable plugin - https://github.com/cosmocode/edittable/network My translation is missing.
I translated imagereference plugin and my translation became visible immediately - https://github.com/Klap-in/dokuwiki-plugin-imagereference/network

**Comment by Klap-in** [comment]
Submitting a random change via the translation tool seems to work for me. The commit is appearing online. 
https://github.com/dokuwiki-translate/dokuwiki_plugin_wrap/commit/bb884211a6a03b7569935d2d3a3998623a59115b

and gets its pull request:
https://github.com/selfthinker/dokuwiki_plugin_wrap/pull/139

@nelidimitrova could you retry to submit a translation? Please keep care of the steps you perform, error or other information that could be maybe helpful. Thanks! 
Note also the time when you try it, then we could eventually check the error logs.

**Comment by Klap-in** [comment]
Please test again, if you experienced it again, please record here steps that could help me reproducing it.

In that case, add also additional information about: browser, operating system, time of submit.
