### ISSUE TITLE
Problem with automatic update

### ISSUE THREAD

**Issue by TorMec** [dokufreaks/dokuwiki-translation#88]
Hi,
28/11/2015 I received a translation, in Czech, about my plugin (PyCode), but it's not listed yet in http://translate.dokuwiki.org/plugin/pycode, even though I have been able to upload the language patch inside the `/lang/` folder.

How long does it take to view the translation in translate.dokuwiki.org?

Also, 15/10/2015 I received an e-mail from translate@dokuwiki.org which says:
```
Hello,

the automatic update of your  failed.
I wasn't able to pull from the given repository.
Please ensure that the the given URL is publicly accessable.

The git URL was

Regards,
DokuWiki Translation Tool
```
I suppose there is (still) a problem with the url of my repo (You already gave me a good help here #84).

Thanks

**Comment by TorMec** [comment]
Since until now there wasn't any automatic update, is it possible to remake a fresh registration of my plugin (I mean cancel completely and then register again it).

Also, could you write a detailed wiki page about git's commands to use in order to merge a pull request coming from `translate.dokuwiki`?
Because I received two translations: the first one was merged correctly while the last one it's not listed, so, maybe, I did something wrong.

**Comment by Klap-in** [comment]
Where do you see your pull requests? 
If I read the code correctly, you will get only mails with patches, you won't?

In the code of the translation tool defines RepositoryBehavior classes for socalled 'github' and 'plain' behavior. See https://github.com/dokufreaks/dokuwiki-translation/tree/master/src/org/dokuwiki/translatorBundle/Services/Repository/Behavior
Looking in these classes it performes pull requests for github. For other repositories it will only send mails with patches.

So for bitbucket the tool is not (yet) performing pull requests.

**Comment by TorMec** [comment]
> If I read the code correctly, you will get only mails with patches, you won't?
Right.

> So for bitbucket the tool is not (yet) performing pull requests.
Got it. So, do you think that this problem is the cause of the non-update of the translations of my plugin?
Is it possible to force (manually) the translation tool to "scan" my bitbucket repository?

**Comment by Klap-in** [comment]
Updates applied to your repository should be found by the translation tool. I will ask our server admins if they could check the logs for us.

At https://bitbucket.org/Torpedo/pycode/commits/all?page=2 is saw indeed the applied patches.

Maybe the error count of your plugin in the translation tool is (still) too high/not reset or maybe errors are created by something unknown. Only well-known error are mailed, the other errors are only (partly) stored in translation tool.

**Comment by TorMec** [comment]
Last week I've uploaded two translations and both them have been immediately applied.
So, for me, the problem is no longer persistent.

**Comment by Klap-in** [comment]
I see still some strange errors and messages on the server, but I got the impression as well that the translation process is working sufficient. Nice!
