### ISSUE TITLE
Action submit dosen't worked in incognito mode

### ISSUE THREAD

**Issue by araname** [dokufreaks/dokuwiki-translation#89]
Action submit dosen't worked in incognito mode, Chrome.

**Comment by Klap-in** [comment]
There is a listener on the submit event:
https://github.com/dokufreaks/dokuwiki-translation/blob/master/src/org/dokuwiki/translatorBundle/Resources/public/js/translationWarnings.js#L116
But if I test on my machine I could submit a translation. Note when you have blank fields somewhere in the form, that the browser shows directly a warning above the field that it is required...

Could you explain what you mean by "doesn't work". What did you expect, and what happens?

**Comment by Klap-in** [comment]
More info is needed.
